export const styles = {
  body: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    minHeight: '100vh',
    fontFamily: 'Arial, sans-serif',
  },
  nav: {
    background: '#fff',
    padding: '20px 40px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 50,
  },
  navTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#667eea',
    margin: 0,
  },
  navLink: {
    textDecoration: 'none',
    color: '#333',
    fontWeight: '600',
    fontSize: '16px',
  },
  quoteSection: {
    background: '#fff',
    borderRadius: '20px',
    padding: '60px 40px',
    textAlign: 'center',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
    marginBottom: '60px',
  },
  quoteTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 30px 0',
  },
  quoteText: {
    fontSize: '24px',
    color: '#667eea',
    fontWeight: '600',
    marginBottom: '30px',
    fontStyle: 'italic',
    lineHeight: '1.8',
  },
  button: {
    background: '#667eea',
    color: '#fff',
    border: 'none',
    padding: '16px 40px',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '18px',
    boxShadow: '0 4px 15px rgba(102, 126, 234, 0.4)',
  },
  card: {
    background: '#fff',
    borderRadius: '16px',
    padding: '40px',
    boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
    cursor: 'pointer',
  },
  cardTitle: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 15px 0',
  },
  footer: {
    background: '#fff',
    borderTop: '1px solid #eee',
    padding: '60px 20px',
    marginTop: '80px',
  },
};
